import 'package:flutter/material.dart';
import 'package:quitvape/services/quit_service.dart';
import 'package:quitvape/main.dart';

class DoctorReportScreen extends StatelessWidget {
  const DoctorReportScreen({super.key});

  @override
  Widget build(BuildContext context) {
    final days = QuitService.getQuitDuration().inDays;
    final moneySaved = QuitService.getMoneySaved();
    final cigsAvoided = QuitService.getCigsAvoided();
    final cravingsBeaten = QuitService.getCravingsResisted();
    final milestones = QuitService.getMilestones().where((m) => m['achieved'] as bool).toList();

    return Scaffold(
      backgroundColor: AppStyle.bg,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(Icons.arrow_back_rounded, color: Colors.white),
          onPressed: () => Navigator.pop(context),
        ),
        title: const Text('🏥 Health Report', style: TextStyle(fontWeight: FontWeight.bold, color: Colors.white)),
        centerTitle: true,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(20),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            // Report header
            Container(
              width: double.infinity,
              padding: const EdgeInsets.all(24),
              decoration: BoxDecoration(
                color: Colors.white,
                borderRadius: BorderRadius.circular(20),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Row(
                    children: [
                      Container(
                        width: 50,
                        height: 50,
                        decoration: BoxDecoration(
                          color: const Color(0xFF00B87D).withOpacity(0.1),
                          borderRadius: BorderRadius.circular(12),
                        ),
                        child: const Center(child: Text('🏥', style: TextStyle(fontSize: 28))),
                      ),
                      const SizedBox(width: 14),
                      const Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text('SMOKING CESSATION',
                                style: TextStyle(fontSize: 11, letterSpacing: 2, color: Colors.grey, fontWeight: FontWeight.bold)),
                            Text('Progress Report',
                                style: TextStyle(fontSize: 22, fontWeight: FontWeight.w800, color: Colors.black)),
                          ],
                        ),
                      ),
                    ],
                  ),
                  const Divider(height: 32),
                  _reportRow('Smoke-free duration', '$days days'),
                  _reportRow('Cigarettes avoided', '$cigsAvoided'),
                  _reportRow('Money saved', '\$${moneySaved.toStringAsFixed(2)}'),
                  _reportRow('Cravings overcome', '$cravingsBeaten'),
                  _reportRow('Health milestones', '${milestones.length}/12 achieved'),
                  const Divider(height: 32),
                  const Text('HEALTH IMPROVEMENTS',
                      style: TextStyle(fontSize: 11, letterSpacing: 1.5, color: Colors.grey, fontWeight: FontWeight.bold)),
                  const SizedBox(height: 12),
                  ...milestones.take(5).map((m) => Padding(
                        padding: const EdgeInsets.symmetric(vertical: 4),
                        child: Row(
                          children: [
                            const Text('✅', style: TextStyle(fontSize: 14)),
                            const SizedBox(width: 8),
                            Expanded(
                              child: Text('${m['title']}: ${m['desc']}',
                                  style: const TextStyle(fontSize: 13, color: Colors.black87)),
                            ),
                          ],
                        ),
                      )),
                  const SizedBox(height: 16),
                  Container(
                    padding: const EdgeInsets.all(14),
                    decoration: BoxDecoration(
                      color: const Color(0xFF00B87D).withOpacity(0.08),
                      borderRadius: BorderRadius.circular(12),
                    ),
                    child: const Text(
                      'Generated by QuitVape • Show this to your healthcare provider',
                      style: TextStyle(fontSize: 12, color: Colors.grey, fontStyle: FontStyle.italic),
                      textAlign: TextAlign.center,
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 20),
            SizedBox(
              width: double.infinity,
              height: 56,
              child: Container(
                decoration: BoxDecoration(
                  gradient: AppStyle.gradientEmerald,
                  borderRadius: BorderRadius.circular(16),
                ),
                child: ElevatedButton(
                  onPressed: () {
                    ScaffoldMessenger.of(context).showSnackBar(
                      const SnackBar(content: Text('📄 PDF export coming in next update!')),
                    );
                  },
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.transparent,
                    shadowColor: Colors.transparent,
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
                  ),
                  child: const Text('📄 Export as PDF',
                      style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16, color: Colors.black)),
                ),
              ),
            ),
            const SizedBox(height: 20),
          ],
        ),
      ),
    );
  }

  Widget _reportRow(String label, String value) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          Text(label, style: const TextStyle(color: Colors.grey, fontSize: 14)),
          Text(value, style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 15, color: Colors.black)),
        ],
      ),
    );
  }
}
